spring:
  config:
    activate:
      on-profile:
        - prod
logging:
  structured:
    format:
      console: ecs # elastic common schema
  level:
    '[io.opentelemetry.exporter]': DEBUG
    '[io.opentelemetry.sdk.trace.export]': DEBUG

management:
  tracing:
    sampling:
      probability: 1.0 # no sampling — see libs/faro's equivalent decision; traffic is far under free-tier limits either way

relay:
  cors:
    allowed-origins: 'https://lean.dev.br'
