spring:
  application:
    name: relay-service
  threads:
    virtual:
      enabled: true

relay:
  cors:
    allowed-origins: '*'
  room-ttl: 5m
  max-updates-per-room: 1000

logging:
  level:
    '[br.dev.lean.relay]': DEBUG
