/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/destinations': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List all destinations */
    get: operations['listDestinations'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/destinations/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get a single destination by id */
    get: operations['getDestination'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    Destination: {
      /** @example fernando-de-noronha-br */
      id: string;
      /** @example Fernando de Noronha */
      name: string;
      /** @example Brazil */
      country: string;
      /** @example Volcanic archipelago with turquoise bays and spinner dolphins. */
      description: string;
      /** @example /images/fernando-de-noronha.jpg */
      imageUrl: string;
      /**
       * Format: double
       * @example -3.85
       */
      latitude?: number;
      /**
       * Format: double
       * @example -32.42
       */
      longitude?: number;
      weather?: components['schemas']['Weather'];
    };
    Weather: {
      /**
       * Format: double
       * @example 27.4
       */
      temperatureC: number;
      /**
       * @description WMO weather interpretation code.
       * @example 1
       */
      weatherCode: number;
    };
    Problem: {
      /** Format: uri */
      type?: string;
      title: string;
      status: number;
      detail?: string;
      /** Format: uri-reference */
      instance?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  listDestinations: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Destination list */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Destination'][];
        };
      };
      /** @description Unexpected error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
    };
  };
  getDestination: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Destination detail */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Destination'];
        };
      };
      /** @description Destination not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
    };
  };
}
